# Generated by Django 3.2.2 on 2021-05-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='img_poster',
        ),
        migrations.RemoveField(
            model_name='services',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
    ]
