# Generated by Django 3.2.2 on 2021-05-08 07:15

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210508_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default='default description'),
        ),
        migrations.AddField(
            model_name='services',
            name='img_poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='service.services'),
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='default slug', max_length=100),
        ),
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(default='default title', max_length=100),
        ),
    ]
