# Generated by Django 3.2.2 on 2021-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210508_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Последняя работа', 'verbose_name_plural': 'Последние работы'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='level',
        ),
        migrations.RemoveField(
            model_name='services',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='services',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='services',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='services',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='services',
            name='category_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
