# Generated by Django 3.2.2 on 2021-05-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
