# Generated by Django 3.2.2 on 2021-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0008_auto_20210508_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='can be your product', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('img_poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинки')),
            ],
            options={
                'verbose_name': 'Наш продукт',
                'verbose_name_plural': 'Наши продукты',
            },
        ),
    ]
