# Generated by Django 3.2.2 on 2021-05-08 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_category_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('mail', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Мейл')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Whatsapp')),
                ('instagram', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='instagram')),
                ('twitter', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='twitter')),
                ('facebook', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='facebook')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='может быть ваша новость', max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('img_poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинки')),
            ],
        ),
        migrations.CreateModel(
            name='submit_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('mail', models.EmailField(max_length=255, unique=True, verbose_name='Мейл')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='services',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(default='Введите название услуги', max_length=255, null=True, verbose_name='Название'),
        ),
    ]
